server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/db_spring?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
#mybatis setting
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dzg.entity
logging:
  level:
    com:
      dzg:
        mapper: debug
